name: maisoku
description: Maisoku AI v1.0

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.8

  # HTTP通信 (Cloud Run API + Google Maps API)
  http: ^1.2.2

  # 位置情報・GPS
  geolocator: ^12.0.0

  # Camera & Image Processing
  camera: ^0.10.5+9
  image_picker: ^1.0.7
  
  # 権限管理
  permission_handler: ^11.3.1

  # Firebase完全統合
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  google_sign_in: ^6.3.0
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2
  firebase_crashlytics: ^4.1.3
  
  # AI機能 (Legacy Gemini + Cloud Run)
  google_generative_ai: ^0.4.6
  
  # 音声読み上げ
  flutter_tts: ^4.1.0
  
  # ファイル処理
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # コード品質・リンティング
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # アセット設定（将来の拡張用）
  # assets:
  #   - images/
  #   - icons/

  # フォント設定（Material Design 3対応）
  # fonts:
  #   - family: NotoSansJP
  #     fonts:
  #       - asset: fonts/NotoSansJP-Regular.ttf
  #       - asset: fonts/NotoSansJP-Bold.ttf
  #         weight: 700