# cloudbuild.yaml - MaisokuAI v1.0 Cloud Build Configuration (Google Maps API対応)

steps:
  # Docker イメージビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'gcr.io/$PROJECT_ID/real-estate-flyer-api:$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/real-estate-flyer-api:latest',
      '.'
    ]

  # イメージをContainer Registryにプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/real-estate-flyer-api:$BUILD_ID']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/real-estate-flyer-api:latest']

  # Cloud Runにデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'real-estate-flyer-api',
      '--image', 'gcr.io/$PROJECT_ID/real-estate-flyer-api:$BUILD_ID',
      '--region', 'asia-northeast1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--memory', '1Gi',
      '--cpu', '1',     
      '--max-instances', '10',
      '--timeout', '300',
      '--set-env-vars', 
      'GOOGLE_CLOUD_PROJECT=$PROJECT_ID,VERTEX_AI_LOCATION=us-central1,FIREBASE_PROJECT_ID=$PROJECT_ID',
      '--set-secrets',
      'FIREBASE_SERVICE_ACCOUNT_KEY=firebase-service-account:latest,GOOGLE_MAPS_API_KEY=google-maps-api-key:latest'
    ]

# ビルド設定
options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'