version: '3.8'

services:
  maisoku-api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - PORT=8080
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
